automation:
  - id: voicepe_force_mute
    alias: Voice PE - Force mute speaker
    mode: restart
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: media_player.home_assistant_voice_0994f1_media_player
    action:
      - service: media_player.volume_set
        target:
          entity_id: media_player.home_assistant_voice_0994f1_media_player
        data:
          volume_level: 0.0
