script:
  voice_reply:
    alias: Voice - Speak reply (Sonos backbone)
    mode: queued
    fields:
      message:
        description: Message to speak
      target:
        description: Optional media_player override
    sequence:
      - variables:
          msg: "{{ message | default('') }}"
          resolved_tgt: >-
            {% if target is defined and target | string | length > 0 %}
              {{ target }}
            {% else %}
              media_player.living_room
            {% endif %}
      - service: tts.speak
        data:
          platform: piper
          media_player_entity_id: "{{ resolved_tgt }}"
          message: "{{ msg }}"
          cache: false

automation:
  - alias: Voice - Speak ChatGPT output
    mode: queued
    trigger:
      - platform: state
        entity_id: input_text.chatgpt_output
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state | length > 0 }}"
    action:
      - service: script.voice_reply
        data:
          message: "{{ trigger.to_state.state }}"
