input_boolean:
  unlock_pending:
    name: Unlock pending (voice confirm)
    icon: mdi:lock-open-alert

script:
  lock_all_doors:
    alias: Locks - Lock all doors (voice)
    mode: single
    sequence:
      - service: lock.lock
        target:
          entity_id: group.all_locks
      - service: tts.speak
        data:
          message: "Locking all doors."

  unlock_doors_request:
    alias: Locks - Unlock request (voice)
    mode: single
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.unlock_pending
      - service: tts.speak
        data:
          message: "Unlock requested. Say confirm unlock within 30 seconds to proceed."

  unlock_doors_confirm:
    alias: Locks - Unlock confirm (voice)
    mode: single
    sequence:
      - condition: state
        entity_id: input_boolean.unlock_pending
        state: "on"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.unlock_pending
      - service: lock.unlock
        target:
          entity_id: group.all_locks
      - service: tts.speak
        data:
          message: "Unlocking all doors."

  unlock_doors_cancel:
    alias: Locks - Unlock cancel (voice)
    mode: single
    sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.unlock_pending
      - service: tts.speak
        data:
          message: "Unlock cancelled."

automation:
  - id: unlock_pending_timeout
    alias: Locks - Unlock confirm timeout
    mode: restart
    trigger:
      - platform: state
        entity_id: input_boolean.unlock_pending
        to: "on"
    action:
      - delay: "00:00:30"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.unlock_pending
      - service: tts.speak
        data:
          message: "Unlock request expired."
